### ISSUE TITLE
Seminario1-revGladimir

### ISSUE THREAD

**Issue by gladimircc** [JoseAntonioLemos/CEI-Controle-para-Eletronica-Integrado#2]
**Sugestões**

- [ ] Criar funcionalidade para organizar a ordem de atendimento dos chamados de acordo com critérios pré-estabelecidos

**Comment by JoseAntonioLemos** [comment]
Alterada a imagem do Senac RS
Definido relatórios do sistema e mais funcionalidades
Definido mais funcionalidades "inteligentes"
