### ISSUE TITLE
Seminario3-revGladimir

### ISSUE THREAD

**Issue by gladimircc** [JoseAntonioLemos/CEI-Controle-para-Eletronica-Integrado#3]
- [ ] Fazer ajustes na escrita conforme documento (anexo).
[Lemos.docx](https://github.com/JoseAntonioLemos/CEI-Controle-para-Eletronica-Integrado/files/2172278/Lemos.docx)

**Comment by JoseAntonioLemos** [comment]
Corrigido

**Comment by JoseAntonioLemos** [comment]
Foi corrigido
