### ISSUE TITLE
SeminárioFinal_revAngelo

### ISSUE THREAD

**Issue by angelogluz** [JoseAntonioLemos/CEI-Controle-para-Eletronica-Integrado#4]
**Correções**
* [x] Onde fica o acompanhamento da OS? Registro de Andamento
* [ ] E a avaliação do atendimento?
* [x] Eu acho que deveria interagir, mesmo que pouco, com o usuário (que no caso dos similares deve ser o envio de e-mail)
* [x] Colocar imagens dos sistemas similares
* [x] Pensar em novas funcionalidades

**Considerações**
* Casos de uso - O Cliente não interage com o sistema? Nem para visualizar o andamento da OS
* Cores do sistema estranhas
* Logo está estranho (no sistema)
* Como sistemas similares também

**Comment by JoseAntonioLemos** [comment]
!. Não aparecia antes o status da OS por que não tinha pronto o CRUD de OS
2. Foi anexado nos requisitos funcionais o envio de email
3.Foi colocado as imagens de telas de cada sistema similar
4. Foi modificado todas as cores 
5. Foi colocado como similar o trabalho do Maicon Resende Martins
6. Com a modificação das cores foi corrigido a cor do Logo
7. Foi adicionado novas funcionalidades
Financeiro 
Relatórios de Vendas
Relatórios de Serviço
Relatórios Financeiro
CRUD Configurações
CRUD Financeiro
Desenvolver envio de E-mail
