### ISSUE TITLE
BancaFInal - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [JoseAntonioLemos/CEI-Controle-para-Eletronica-Integrado#5]
Angelo:
1) Atualizar o status da OS
2) Cliente interagir com o sistema: receber e-mail de confirmação
3) Trocar cinza por azul
4) Citar o trabalho do Maicon
5) Consertar o Logo

**Comment by JoseAntonioLemos** [comment]
!. Não aparecia antes o status da OS por que não tinha pronto o CRUD de OS
2. Foi anexado nos requisitos funcionais o envio de email
3. Foi modificado todas as cores 
4. Foi colocado com similar o trabalho do Maicon Resende Martins
5. Com a modificação das cores foi corrigido a cor do Logo

**Comment by pluzzardi** [comment]
Beleza, José, boa sorte na banca.

Fica bem calmo.

[][]’s

Prof. Luzzardi

Em sáb, 22 de set de 2018 às 08:33, JoseAntonioLemos <
notifications@github.com> escreveu:

**Comment by pluzzardi** [comment]
Okay José, aguarde ...

[][]'s
Luzzardi

Em qui, 25 de out de 2018 às 00:24, JoseAntonioLemos <
notifications@github.com> escreveu:
